sonar.projectKey=otvprint-unifor_kanvix
sonar.organization=otvprint-unifor

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.exclusions=\
coverage/**,\
.next/**,\
**/*.test.ts,\
**/*.test.tsx

sonar.coverage.exclusions=\
**

# coverage desativado
# sonar.javascript.lcov.reportPaths=coverage/lcov.info