sonar.projectKey=otvprint-unifor_kanvix
sonar.organization=otvprint-unifor

sonar.sources=src

sonar.tests=src

sonar.test.inclusions=**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8